/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.enums.IdProvider;
import au.org.raid.db.jooq.enums.UserRole;
import au.org.raid.db.jooq.tables.AppUser;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppUserRecord extends UpdatableRecordImpl<AppUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.app_user.id</code>.
     */
    public AppUserRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.app_user.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>api_svc.app_user.service_point_id</code>.
     */
    public AppUserRecord setServicePointId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.app_user.service_point_id</code>.
     */
    public Long getServicePointId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>api_svc.app_user.email</code>. should be renamed to
     * "description" or some such.  api-keys do not and orcid
     *   sign-ins might not have email address
     */
    public AppUserRecord setEmail(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.app_user.email</code>. should be renamed to
     * "description" or some such.  api-keys do not and orcid
     *   sign-ins might not have email address
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>api_svc.app_user.client_id</code>.
     */
    public AppUserRecord setClientId(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.app_user.client_id</code>.
     */
    public String getClientId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>api_svc.app_user.subject</code>.
     */
    public AppUserRecord setSubject(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.app_user.subject</code>.
     */
    public String getSubject() {
        return (String) get(4);
    }

    /**
     * Setter for <code>api_svc.app_user.id_provider</code>. not a real identity
     * field, its just redundant info we figure it out from
     *   the clientId or issuer and store it for easy analysis
     */
    public AppUserRecord setIdProvider(IdProvider value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.app_user.id_provider</code>. not a real identity
     * field, its just redundant info we figure it out from
     *   the clientId or issuer and store it for easy analysis
     */
    public IdProvider getIdProvider() {
        return (IdProvider) get(5);
    }

    /**
     * Setter for <code>api_svc.app_user.role</code>.
     */
    public AppUserRecord setRole(UserRole value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.app_user.role</code>.
     */
    public UserRole getRole() {
        return (UserRole) get(6);
    }

    /**
     * Setter for <code>api_svc.app_user.enabled</code>.
     */
    public AppUserRecord setEnabled(Boolean value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.app_user.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>api_svc.app_user.token_cutoff</code>. Any endpoint call
     * with a bearer token issued after this point will be
     *   rejected. Any authentication attempt after this point will be rejected.
     */
    public AppUserRecord setTokenCutoff(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.app_user.token_cutoff</code>. Any endpoint call
     * with a bearer token issued after this point will be
     *   rejected. Any authentication attempt after this point will be rejected.
     */
    public LocalDateTime getTokenCutoff() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>api_svc.app_user.date_created</code>.
     */
    public AppUserRecord setDateCreated(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.app_user.date_created</code>.
     */
    public LocalDateTime getDateCreated() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppUserRecord
     */
    public AppUserRecord() {
        super(AppUser.APP_USER);
    }

    /**
     * Create a detached, initialised AppUserRecord
     */
    public AppUserRecord(Long id, Long servicePointId, String email, String clientId, String subject, IdProvider idProvider, UserRole role, Boolean enabled, LocalDateTime tokenCutoff, LocalDateTime dateCreated) {
        super(AppUser.APP_USER);

        setId(id);
        setServicePointId(servicePointId);
        setEmail(email);
        setClientId(clientId);
        setSubject(subject);
        setIdProvider(idProvider);
        setRole(role);
        setEnabled(enabled);
        setTokenCutoff(tokenCutoff);
        setDateCreated(dateCreated);
    }
}
