/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.Contributor;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContributorRecord extends UpdatableRecordImpl<ContributorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.contributor.id</code>.
     */
    public ContributorRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.contributor.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.contributor.pid</code>.
     */
    public ContributorRecord setPid(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.contributor.pid</code>.
     */
    public String getPid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.contributor.schema_id</code>.
     */
    public ContributorRecord setSchemaId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.contributor.schema_id</code>.
     */
    public Integer getSchemaId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>api_svc.contributor.status</code>.
     */
    public ContributorRecord setStatus(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.contributor.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContributorRecord
     */
    public ContributorRecord() {
        super(Contributor.CONTRIBUTOR);
    }

    /**
     * Create a detached, initialised ContributorRecord
     */
    public ContributorRecord(Integer id, String pid, Integer schemaId, String status) {
        super(Contributor.CONTRIBUTOR);

        setId(id);
        setPid(pid);
        setSchemaId(schemaId);
        setStatus(status);
    }
}
