/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.ContributorRole;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContributorRoleRecord extends UpdatableRecordImpl<ContributorRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.contributor_role.id</code>.
     */
    public ContributorRoleRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.contributor_role.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.contributor_role.uri</code>.
     */
    public ContributorRoleRecord setUri(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.contributor_role.uri</code>.
     */
    public String getUri() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.contributor_role.schema_id</code>.
     */
    public ContributorRoleRecord setSchemaId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.contributor_role.schema_id</code>.
     */
    public Integer getSchemaId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContributorRoleRecord
     */
    public ContributorRoleRecord() {
        super(ContributorRole.CONTRIBUTOR_ROLE);
    }

    /**
     * Create a detached, initialised ContributorRoleRecord
     */
    public ContributorRoleRecord(Integer id, String uri, Integer schemaId) {
        super(ContributorRole.CONTRIBUTOR_ROLE);

        setId(id);
        setUri(uri);
        setSchemaId(schemaId);
    }
}
