/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.ContributorPosition;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContributorPositionRecord extends UpdatableRecordImpl<ContributorPositionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.contributor_position.id</code>.
     */
    public ContributorPositionRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.contributor_position.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.contributor_position.uri</code>.
     */
    public ContributorPositionRecord setUri(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.contributor_position.uri</code>.
     */
    public String getUri() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.contributor_position.schema_id</code>.
     */
    public ContributorPositionRecord setSchemaId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.contributor_position.schema_id</code>.
     */
    public Integer getSchemaId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContributorPositionRecord
     */
    public ContributorPositionRecord() {
        super(ContributorPosition.CONTRIBUTOR_POSITION);
    }

    /**
     * Create a detached, initialised ContributorPositionRecord
     */
    public ContributorPositionRecord(Integer id, String uri, Integer schemaId) {
        super(ContributorPosition.CONTRIBUTOR_POSITION);

        setId(id);
        setUri(uri);
        setSchemaId(schemaId);
    }
}
