/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.Language;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LanguageRecord extends UpdatableRecordImpl<LanguageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.language.id</code>.
     */
    public LanguageRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.language.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.language.code</code>.
     */
    public LanguageRecord setCode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.language.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.language.name</code>.
     */
    public LanguageRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.language.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>api_svc.language.schema_id</code>.
     */
    public LanguageRecord setSchemaId(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.language.schema_id</code>.
     */
    public Integer getSchemaId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LanguageRecord
     */
    public LanguageRecord() {
        super(Language.LANGUAGE);
    }

    /**
     * Create a detached, initialised LanguageRecord
     */
    public LanguageRecord(Integer id, String code, String name, Integer schemaId) {
        super(Language.LANGUAGE);

        setId(id);
        setCode(code);
        setName(name);
        setSchemaId(schemaId);
    }
}
