/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.OrganisationRole;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrganisationRoleRecord extends UpdatableRecordImpl<OrganisationRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.organisation_role.id</code>.
     */
    public OrganisationRoleRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.organisation_role.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.organisation_role.uri</code>.
     */
    public OrganisationRoleRecord setUri(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.organisation_role.uri</code>.
     */
    public String getUri() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.organisation_role.schema_id</code>.
     */
    public OrganisationRoleRecord setSchemaId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.organisation_role.schema_id</code>.
     */
    public Integer getSchemaId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrganisationRoleRecord
     */
    public OrganisationRoleRecord() {
        super(OrganisationRole.ORGANISATION_ROLE);
    }

    /**
     * Create a detached, initialised OrganisationRoleRecord
     */
    public OrganisationRoleRecord(Integer id, String uri, Integer schemaId) {
        super(OrganisationRole.ORGANISATION_ROLE);

        setId(id);
        setUri(uri);
        setSchemaId(schemaId);
    }
}
