/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.Organisation;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrganisationRecord extends UpdatableRecordImpl<OrganisationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.organisation.id</code>.
     */
    public OrganisationRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.organisation.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.organisation.pid</code>.
     */
    public OrganisationRecord setPid(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.organisation.pid</code>.
     */
    public String getPid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.organisation.schema_id</code>.
     */
    public OrganisationRecord setSchemaId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.organisation.schema_id</code>.
     */
    public Integer getSchemaId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrganisationRecord
     */
    public OrganisationRecord() {
        super(Organisation.ORGANISATION);
    }

    /**
     * Create a detached, initialised OrganisationRecord
     */
    public OrganisationRecord(Integer id, String pid, Integer schemaId) {
        super(Organisation.ORGANISATION);

        setId(id);
        setPid(pid);
        setSchemaId(schemaId);
    }
}
