/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.RaidTraditionalKnowledgeLabel;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaidTraditionalKnowledgeLabelRecord extends UpdatableRecordImpl<RaidTraditionalKnowledgeLabelRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.raid_traditional_knowledge_label.id</code>.
     */
    public RaidTraditionalKnowledgeLabelRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_traditional_knowledge_label.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.raid_traditional_knowledge_label.handle</code>.
     */
    public RaidTraditionalKnowledgeLabelRecord setHandle(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_traditional_knowledge_label.handle</code>.
     */
    public String getHandle() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>api_svc.raid_traditional_knowledge_label.traditional_knowledge_label_id</code>.
     */
    public RaidTraditionalKnowledgeLabelRecord setTraditionalKnowledgeLabelId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>api_svc.raid_traditional_knowledge_label.traditional_knowledge_label_id</code>.
     */
    public Integer getTraditionalKnowledgeLabelId() {
        return (Integer) get(2);
    }

    /**
     * Setter for
     * <code>api_svc.raid_traditional_knowledge_label.traditional_knowledge_label_schema_id</code>.
     */
    public RaidTraditionalKnowledgeLabelRecord setTraditionalKnowledgeLabelSchemaId(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>api_svc.raid_traditional_knowledge_label.traditional_knowledge_label_schema_id</code>.
     */
    public Integer getTraditionalKnowledgeLabelSchemaId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaidTraditionalKnowledgeLabelRecord
     */
    public RaidTraditionalKnowledgeLabelRecord() {
        super(RaidTraditionalKnowledgeLabel.RAID_TRADITIONAL_KNOWLEDGE_LABEL);
    }

    /**
     * Create a detached, initialised RaidTraditionalKnowledgeLabelRecord
     */
    public RaidTraditionalKnowledgeLabelRecord(Integer id, String handle, Integer traditionalKnowledgeLabelId, Integer traditionalKnowledgeLabelSchemaId) {
        super(RaidTraditionalKnowledgeLabel.RAID_TRADITIONAL_KNOWLEDGE_LABEL);

        setId(id);
        setHandle(handle);
        setTraditionalKnowledgeLabelId(traditionalKnowledgeLabelId);
        setTraditionalKnowledgeLabelSchemaId(traditionalKnowledgeLabelSchemaId);
    }
}
