/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.RaidAlternateUrl;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaidAlternateUrlRecord extends UpdatableRecordImpl<RaidAlternateUrlRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.raid_alternate_url.handle</code>.
     */
    public RaidAlternateUrlRecord setHandle(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_alternate_url.handle</code>.
     */
    public String getHandle() {
        return (String) get(0);
    }

    /**
     * Setter for <code>api_svc.raid_alternate_url.url</code>.
     */
    public RaidAlternateUrlRecord setUrl(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_alternate_url.url</code>.
     */
    public String getUrl() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaidAlternateUrlRecord
     */
    public RaidAlternateUrlRecord() {
        super(RaidAlternateUrl.RAID_ALTERNATE_URL);
    }

    /**
     * Create a detached, initialised RaidAlternateUrlRecord
     */
    public RaidAlternateUrlRecord(String handle, String url) {
        super(RaidAlternateUrl.RAID_ALTERNATE_URL);

        setHandle(handle);
        setUrl(url);
    }
}
