/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.RaidSubject;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaidSubjectRecord extends UpdatableRecordImpl<RaidSubjectRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.raid_subject.id</code>.
     */
    public RaidSubjectRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_subject.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.raid_subject.handle</code>.
     */
    public RaidSubjectRecord setHandle(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_subject.handle</code>.
     */
    public String getHandle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.raid_subject.subject_type_id</code>.
     */
    public RaidSubjectRecord setSubjectTypeId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_subject.subject_type_id</code>.
     */
    public String getSubjectTypeId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>api_svc.raid_subject.subject_type_schema_id</code>.
     */
    public RaidSubjectRecord setSubjectTypeSchemaId(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_subject.subject_type_schema_id</code>.
     */
    public Integer getSubjectTypeSchemaId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaidSubjectRecord
     */
    public RaidSubjectRecord() {
        super(RaidSubject.RAID_SUBJECT);
    }

    /**
     * Create a detached, initialised RaidSubjectRecord
     */
    public RaidSubjectRecord(Integer id, String handle, String subjectTypeId, Integer subjectTypeSchemaId) {
        super(RaidSubject.RAID_SUBJECT);

        setId(id);
        setHandle(handle);
        setSubjectTypeId(subjectTypeId);
        setSubjectTypeSchemaId(subjectTypeSchemaId);
    }
}
