/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.enums.Metaschema;
import au.org.raid.db.jooq.tables.Raid;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaidRecord extends UpdatableRecordImpl<RaidRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.raid.handle</code>. Holds the handle (i.e. just
     * prefix/suffix) not the URL.  Usually quite  short in production, but the
     * max length is set to accommodate int and load testing.
     */
    public RaidRecord setHandle(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.handle</code>. Holds the handle (i.e. just
     * prefix/suffix) not the URL.  Usually quite  short in production, but the
     * max length is set to accommodate int and load testing.
     */
    public String getHandle() {
        return (String) get(0);
    }

    /**
     * Setter for <code>api_svc.raid.service_point_id</code>.
     */
    public RaidRecord setServicePointId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.service_point_id</code>.
     */
    public Long getServicePointId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>api_svc.raid.url</code>. The value that we set as the
     * `URL` property via ARDC APIDS.
     *   Example: `https://demo.raido-infra.com/raid/123.456/789`.
     *   The global handle regisrty url (e.g.
     * `https://hdl.handle.net/123.456/789`)
     *   will redirect to this value.
     */
    public RaidRecord setUrl(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.url</code>. The value that we set as the
     * `URL` property via ARDC APIDS.
     *   Example: `https://demo.raido-infra.com/raid/123.456/789`.
     *   The global handle regisrty url (e.g.
     * `https://hdl.handle.net/123.456/789`)
     *   will redirect to this value.
     */
    public String getUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>api_svc.raid.url_index</code>. The `index` of the URL
     * property in APIDS. This can be different if we change
     *   how we mint URL values via APIDS.
     */
    public RaidRecord setUrlIndex(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.url_index</code>. The `index` of the URL
     * property in APIDS. This can be different if we change
     *   how we mint URL values via APIDS.
     */
    public Integer getUrlIndex() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>api_svc.raid.primary_title</code>.
     */
    public RaidRecord setPrimaryTitle(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.primary_title</code>.
     */
    public String getPrimaryTitle() {
        return (String) get(4);
    }

    /**
     * Setter for <code>api_svc.raid.confidential</code>.
     */
    public RaidRecord setConfidential(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.confidential</code>.
     */
    public Boolean getConfidential() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>api_svc.raid.metadata_schema</code>. Identifies the
     * structure of the data in the metadata column
     */
    public RaidRecord setMetadataSchema(Metaschema value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.metadata_schema</code>. Identifies the
     * structure of the data in the metadata column
     */
    public Metaschema getMetadataSchema() {
        return (Metaschema) get(6);
    }

    /**
     * Setter for <code>api_svc.raid.metadata</code>.
     */
    public RaidRecord setMetadata(JSONB value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.metadata</code>.
     */
    public JSONB getMetadata() {
        return (JSONB) get(7);
    }

    /**
     * Setter for <code>api_svc.raid.start_date</code>.
     */
    public RaidRecord setStartDate(LocalDate value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.start_date</code>.
     */
    public LocalDate getStartDate() {
        return (LocalDate) get(8);
    }

    /**
     * Setter for <code>api_svc.raid.date_created</code>.
     */
    public RaidRecord setDateCreated(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.date_created</code>.
     */
    public LocalDateTime getDateCreated() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>api_svc.raid.version</code>.
     */
    public RaidRecord setVersion(Integer value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>api_svc.raid.start_date_string</code>.
     */
    public RaidRecord setStartDateString(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.start_date_string</code>.
     */
    public String getStartDateString() {
        return (String) get(11);
    }

    /**
     * Setter for <code>api_svc.raid.end_date</code>.
     */
    public RaidRecord setEndDate(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.end_date</code>.
     */
    public String getEndDate() {
        return (String) get(12);
    }

    /**
     * Setter for <code>api_svc.raid.license</code>.
     */
    public RaidRecord setLicense(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.license</code>.
     */
    public String getLicense() {
        return (String) get(13);
    }

    /**
     * Setter for <code>api_svc.raid.access_type_id</code>.
     */
    public RaidRecord setAccessTypeId(Integer value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.access_type_id</code>.
     */
    public Integer getAccessTypeId() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>api_svc.raid.embargo_expiry</code>.
     */
    public RaidRecord setEmbargoExpiry(LocalDate value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.embargo_expiry</code>.
     */
    public LocalDate getEmbargoExpiry() {
        return (LocalDate) get(15);
    }

    /**
     * Setter for <code>api_svc.raid.access_statement</code>.
     */
    public RaidRecord setAccessStatement(String value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.access_statement</code>.
     */
    public String getAccessStatement() {
        return (String) get(16);
    }

    /**
     * Setter for <code>api_svc.raid.access_statement_language_id</code>.
     */
    public RaidRecord setAccessStatementLanguageId(Integer value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.access_statement_language_id</code>.
     */
    public Integer getAccessStatementLanguageId() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>api_svc.raid.schema_uri</code>.
     */
    public RaidRecord setSchemaUri(String value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.schema_uri</code>.
     */
    public String getSchemaUri() {
        return (String) get(18);
    }

    /**
     * Setter for <code>api_svc.raid.registration_agency_organisation_id</code>.
     */
    public RaidRecord setRegistrationAgencyOrganisationId(Integer value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.registration_agency_organisation_id</code>.
     */
    public Integer getRegistrationAgencyOrganisationId() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>api_svc.raid.owner_organisation_id</code>.
     */
    public RaidRecord setOwnerOrganisationId(Integer value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid.owner_organisation_id</code>.
     */
    public Integer getOwnerOrganisationId() {
        return (Integer) get(20);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaidRecord
     */
    public RaidRecord() {
        super(Raid.RAID);
    }

    /**
     * Create a detached, initialised RaidRecord
     */
    public RaidRecord(String handle, Long servicePointId, String url, Integer urlIndex, String primaryTitle, Boolean confidential, Metaschema metadataSchema, JSONB metadata, LocalDate startDate, LocalDateTime dateCreated, Integer version, String startDateString, String endDate, String license, Integer accessTypeId, LocalDate embargoExpiry, String accessStatement, Integer accessStatementLanguageId, String schemaUri, Integer registrationAgencyOrganisationId, Integer ownerOrganisationId) {
        super(Raid.RAID);

        setHandle(handle);
        setServicePointId(servicePointId);
        setUrl(url);
        setUrlIndex(urlIndex);
        setPrimaryTitle(primaryTitle);
        setConfidential(confidential);
        setMetadataSchema(metadataSchema);
        setMetadata(metadata);
        setStartDate(startDate);
        setDateCreated(dateCreated);
        setVersion(version);
        setStartDateString(startDateString);
        setEndDate(endDate);
        setLicense(license);
        setAccessTypeId(accessTypeId);
        setEmbargoExpiry(embargoExpiry);
        setAccessStatement(accessStatement);
        setAccessStatementLanguageId(accessStatementLanguageId);
        setSchemaUri(schemaUri);
        setRegistrationAgencyOrganisationId(registrationAgencyOrganisationId);
        setOwnerOrganisationId(ownerOrganisationId);
    }
}
