/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.RaidContributor;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaidContributorRecord extends UpdatableRecordImpl<RaidContributorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.raid_contributor.id</code>.
     */
    public RaidContributorRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_contributor.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.raid_contributor.handle</code>.
     */
    public RaidContributorRecord setHandle(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_contributor.handle</code>.
     */
    public String getHandle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.raid_contributor.contributor_id</code>.
     */
    public RaidContributorRecord setContributorId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_contributor.contributor_id</code>.
     */
    public Integer getContributorId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>api_svc.raid_contributor.leader</code>.
     */
    public RaidContributorRecord setLeader(Boolean value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_contributor.leader</code>.
     */
    public Boolean getLeader() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>api_svc.raid_contributor.contact</code>.
     */
    public RaidContributorRecord setContact(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_contributor.contact</code>.
     */
    public Boolean getContact() {
        return (Boolean) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaidContributorRecord
     */
    public RaidContributorRecord() {
        super(RaidContributor.RAID_CONTRIBUTOR);
    }

    /**
     * Create a detached, initialised RaidContributorRecord
     */
    public RaidContributorRecord(Integer id, String handle, Integer contributorId, Boolean leader, Boolean contact) {
        super(RaidContributor.RAID_CONTRIBUTOR);

        setId(id);
        setHandle(handle);
        setContributorId(contributorId);
        setLeader(leader);
        setContact(contact);
    }
}
