/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.RaidHistory;

import java.time.LocalDateTime;

import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaidHistoryRecord extends UpdatableRecordImpl<RaidHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.raid_history.handle</code>.
     */
    public RaidHistoryRecord setHandle(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_history.handle</code>.
     */
    public String getHandle() {
        return (String) get(0);
    }

    /**
     * Setter for <code>api_svc.raid_history.revision</code>.
     */
    public RaidHistoryRecord setRevision(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_history.revision</code>.
     */
    public Integer getRevision() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>api_svc.raid_history.change_type</code>.
     */
    public RaidHistoryRecord setChangeType(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_history.change_type</code>.
     */
    public String getChangeType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>api_svc.raid_history.diff</code>.
     */
    public RaidHistoryRecord setDiff(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_history.diff</code>.
     */
    public String getDiff() {
        return (String) get(3);
    }

    /**
     * Setter for <code>api_svc.raid_history.created</code>.
     */
    public RaidHistoryRecord setCreated(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_history.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<String, Integer, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaidHistoryRecord
     */
    public RaidHistoryRecord() {
        super(RaidHistory.RAID_HISTORY);
    }

    /**
     * Create a detached, initialised RaidHistoryRecord
     */
    public RaidHistoryRecord(String handle, Integer revision, String changeType, String diff, LocalDateTime created) {
        super(RaidHistory.RAID_HISTORY);

        setHandle(handle);
        setRevision(revision);
        setChangeType(changeType);
        setDiff(diff);
        setCreated(created);
    }
}
