/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.RaidSubject;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaidSubjectRecord extends UpdatableRecordImpl<RaidSubjectRecord> implements Record4<Integer, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.raid_subject.id</code>.
     */
    public RaidSubjectRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_subject.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.raid_subject.handle</code>.
     */
    public RaidSubjectRecord setHandle(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_subject.handle</code>.
     */
    public String getHandle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.raid_subject.subject_type_id</code>.
     */
    public RaidSubjectRecord setSubjectTypeId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_subject.subject_type_id</code>.
     */
    public String getSubjectTypeId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>api_svc.raid_subject.subject_type_schema_id</code>.
     */
    public RaidSubjectRecord setSubjectTypeSchemaId(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_subject.subject_type_schema_id</code>.
     */
    public Integer getSubjectTypeSchemaId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return RaidSubject.RAID_SUBJECT.ID;
    }

    @Override
    public Field<String> field2() {
        return RaidSubject.RAID_SUBJECT.HANDLE;
    }

    @Override
    public Field<String> field3() {
        return RaidSubject.RAID_SUBJECT.SUBJECT_TYPE_ID;
    }

    @Override
    public Field<Integer> field4() {
        return RaidSubject.RAID_SUBJECT.SUBJECT_TYPE_SCHEMA_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getHandle();
    }

    @Override
    public String component3() {
        return getSubjectTypeId();
    }

    @Override
    public Integer component4() {
        return getSubjectTypeSchemaId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getHandle();
    }

    @Override
    public String value3() {
        return getSubjectTypeId();
    }

    @Override
    public Integer value4() {
        return getSubjectTypeSchemaId();
    }

    @Override
    public RaidSubjectRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public RaidSubjectRecord value2(String value) {
        setHandle(value);
        return this;
    }

    @Override
    public RaidSubjectRecord value3(String value) {
        setSubjectTypeId(value);
        return this;
    }

    @Override
    public RaidSubjectRecord value4(Integer value) {
        setSubjectTypeSchemaId(value);
        return this;
    }

    @Override
    public RaidSubjectRecord values(Integer value1, String value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaidSubjectRecord
     */
    public RaidSubjectRecord() {
        super(RaidSubject.RAID_SUBJECT);
    }

    /**
     * Create a detached, initialised RaidSubjectRecord
     */
    public RaidSubjectRecord(Integer id, String handle, String subjectTypeId, Integer subjectTypeSchemaId) {
        super(RaidSubject.RAID_SUBJECT);

        setId(id);
        setHandle(handle);
        setSubjectTypeId(subjectTypeId);
        setSubjectTypeSchemaId(subjectTypeSchemaId);
    }
}
