/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.RaidOrganisation;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaidOrganisationRecord extends UpdatableRecordImpl<RaidOrganisationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.raid_organisation.id</code>.
     */
    public RaidOrganisationRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_organisation.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.raid_organisation.handle</code>.
     */
    public RaidOrganisationRecord setHandle(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_organisation.handle</code>.
     */
    public String getHandle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.raid_organisation.organisation_id</code>.
     */
    public RaidOrganisationRecord setOrganisationId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_organisation.organisation_id</code>.
     */
    public Integer getOrganisationId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaidOrganisationRecord
     */
    public RaidOrganisationRecord() {
        super(RaidOrganisation.RAID_ORGANISATION);
    }

    /**
     * Create a detached, initialised RaidOrganisationRecord
     */
    public RaidOrganisationRecord(Integer id, String handle, Integer organisationId) {
        super(RaidOrganisation.RAID_ORGANISATION);

        setId(id);
        setHandle(handle);
        setOrganisationId(organisationId);
    }
}
