/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.RaidOrganisationRole;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaidOrganisationRoleRecord extends UpdatableRecordImpl<RaidOrganisationRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.raid_organisation_role.id</code>.
     */
    public RaidOrganisationRoleRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_organisation_role.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>api_svc.raid_organisation_role.raid_organisation_id</code>.
     */
    public RaidOrganisationRoleRecord setRaidOrganisationId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>api_svc.raid_organisation_role.raid_organisation_id</code>.
     */
    public Integer getRaidOrganisationId() {
        return (Integer) get(1);
    }

    /**
     * Setter for
     * <code>api_svc.raid_organisation_role.organisation_role_id</code>.
     */
    public RaidOrganisationRoleRecord setOrganisationRoleId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>api_svc.raid_organisation_role.organisation_role_id</code>.
     */
    public Integer getOrganisationRoleId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>api_svc.raid_organisation_role.start_date</code>.
     */
    public RaidOrganisationRoleRecord setStartDate(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_organisation_role.start_date</code>.
     */
    public String getStartDate() {
        return (String) get(3);
    }

    /**
     * Setter for <code>api_svc.raid_organisation_role.end_date</code>.
     */
    public RaidOrganisationRoleRecord setEndDate(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_organisation_role.end_date</code>.
     */
    public String getEndDate() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaidOrganisationRoleRecord
     */
    public RaidOrganisationRoleRecord() {
        super(RaidOrganisationRole.RAID_ORGANISATION_ROLE);
    }

    /**
     * Create a detached, initialised RaidOrganisationRoleRecord
     */
    public RaidOrganisationRoleRecord(Integer id, Integer raidOrganisationId, Integer organisationRoleId, String startDate, String endDate) {
        super(RaidOrganisationRole.RAID_ORGANISATION_ROLE);

        setId(id);
        setRaidOrganisationId(raidOrganisationId);
        setOrganisationRoleId(organisationRoleId);
        setStartDate(startDate);
        setEndDate(endDate);
    }
}
