/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.RaidRelatedObjectCategory;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaidRelatedObjectCategoryRecord extends UpdatableRecordImpl<RaidRelatedObjectCategoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.raid_related_object_category.id</code>.
     */
    public RaidRelatedObjectCategoryRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_related_object_category.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>api_svc.raid_related_object_category.raid_related_object_id</code>.
     */
    public RaidRelatedObjectCategoryRecord setRaidRelatedObjectId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>api_svc.raid_related_object_category.raid_related_object_id</code>.
     */
    public Integer getRaidRelatedObjectId() {
        return (Integer) get(1);
    }

    /**
     * Setter for
     * <code>api_svc.raid_related_object_category.related_object_category_id</code>.
     */
    public RaidRelatedObjectCategoryRecord setRelatedObjectCategoryId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>api_svc.raid_related_object_category.related_object_category_id</code>.
     */
    public Integer getRelatedObjectCategoryId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaidRelatedObjectCategoryRecord
     */
    public RaidRelatedObjectCategoryRecord() {
        super(RaidRelatedObjectCategory.RAID_RELATED_OBJECT_CATEGORY);
    }

    /**
     * Create a detached, initialised RaidRelatedObjectCategoryRecord
     */
    public RaidRelatedObjectCategoryRecord(Integer id, Integer raidRelatedObjectId, Integer relatedObjectCategoryId) {
        super(RaidRelatedObjectCategory.RAID_RELATED_OBJECT_CATEGORY);

        setId(id);
        setRaidRelatedObjectId(raidRelatedObjectId);
        setRelatedObjectCategoryId(relatedObjectCategoryId);
    }
}
