/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.RaidRelatedObject;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaidRelatedObjectRecord extends UpdatableRecordImpl<RaidRelatedObjectRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.raid_related_object.id</code>.
     */
    public RaidRelatedObjectRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_related_object.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.raid_related_object.handle</code>.
     */
    public RaidRelatedObjectRecord setHandle(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_related_object.handle</code>.
     */
    public String getHandle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.raid_related_object.related_object_id</code>.
     */
    public RaidRelatedObjectRecord setRelatedObjectId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_related_object.related_object_id</code>.
     */
    public Integer getRelatedObjectId() {
        return (Integer) get(2);
    }

    /**
     * Setter for
     * <code>api_svc.raid_related_object.related_object_type_id</code>.
     */
    public RaidRelatedObjectRecord setRelatedObjectTypeId(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>api_svc.raid_related_object.related_object_type_id</code>.
     */
    public Integer getRelatedObjectTypeId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaidRelatedObjectRecord
     */
    public RaidRelatedObjectRecord() {
        super(RaidRelatedObject.RAID_RELATED_OBJECT);
    }

    /**
     * Create a detached, initialised RaidRelatedObjectRecord
     */
    public RaidRelatedObjectRecord(Integer id, String handle, Integer relatedObjectId, Integer relatedObjectTypeId) {
        super(RaidRelatedObject.RAID_RELATED_OBJECT);

        setId(id);
        setHandle(handle);
        setRelatedObjectId(relatedObjectId);
        setRelatedObjectTypeId(relatedObjectTypeId);
    }
}
