/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.RaidAlternateIdentifier;

import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaidAlternateIdentifierRecord extends UpdatableRecordImpl<RaidAlternateIdentifierRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.raid_alternate_identifier.handle</code>.
     */
    public RaidAlternateIdentifierRecord setHandle(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_alternate_identifier.handle</code>.
     */
    public String getHandle() {
        return (String) get(0);
    }

    /**
     * Setter for <code>api_svc.raid_alternate_identifier.id</code>.
     */
    public RaidAlternateIdentifierRecord setId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_alternate_identifier.id</code>.
     */
    public String getId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.raid_alternate_identifier.type</code>.
     */
    public RaidAlternateIdentifierRecord setType(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_alternate_identifier.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<String, String, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaidAlternateIdentifierRecord
     */
    public RaidAlternateIdentifierRecord() {
        super(RaidAlternateIdentifier.RAID_ALTERNATE_IDENTIFIER);
    }

    /**
     * Create a detached, initialised RaidAlternateIdentifierRecord
     */
    public RaidAlternateIdentifierRecord(String handle, String id, String type) {
        super(RaidAlternateIdentifier.RAID_ALTERNATE_IDENTIFIER);

        setHandle(handle);
        setId(id);
        setType(type);
    }
}
