/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.RaidoOperator;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * any app_user with an email in this table will be considered an operator
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaidoOperatorRecord extends UpdatableRecordImpl<RaidoOperatorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.raido_operator.email</code>.
     */
    public RaidoOperatorRecord setEmail(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raido_operator.email</code>.
     */
    public String getEmail() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaidoOperatorRecord
     */
    public RaidoOperatorRecord() {
        super(RaidoOperator.RAIDO_OPERATOR);
    }

    /**
     * Create a detached, initialised RaidoOperatorRecord
     */
    public RaidoOperatorRecord(String email) {
        super(RaidoOperator.RAIDO_OPERATOR);

        setEmail(email);
    }
}
