/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.RaidContributorPosition;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaidContributorPositionRecord extends UpdatableRecordImpl<RaidContributorPositionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.raid_contributor_position.id</code>.
     */
    public RaidContributorPositionRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_contributor_position.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>api_svc.raid_contributor_position.raid_contributor_id</code>.
     */
    public RaidContributorPositionRecord setRaidContributorId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>api_svc.raid_contributor_position.raid_contributor_id</code>.
     */
    public Integer getRaidContributorId() {
        return (Integer) get(1);
    }

    /**
     * Setter for
     * <code>api_svc.raid_contributor_position.contributor_position_id</code>.
     */
    public RaidContributorPositionRecord setContributorPositionId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>api_svc.raid_contributor_position.contributor_position_id</code>.
     */
    public Integer getContributorPositionId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>api_svc.raid_contributor_position.start_date</code>.
     */
    public RaidContributorPositionRecord setStartDate(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_contributor_position.start_date</code>.
     */
    public String getStartDate() {
        return (String) get(3);
    }

    /**
     * Setter for <code>api_svc.raid_contributor_position.end_date</code>.
     */
    public RaidContributorPositionRecord setEndDate(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_contributor_position.end_date</code>.
     */
    public String getEndDate() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaidContributorPositionRecord
     */
    public RaidContributorPositionRecord() {
        super(RaidContributorPosition.RAID_CONTRIBUTOR_POSITION);
    }

    /**
     * Create a detached, initialised RaidContributorPositionRecord
     */
    public RaidContributorPositionRecord(Integer id, Integer raidContributorId, Integer contributorPositionId, String startDate, String endDate) {
        super(RaidContributorPosition.RAID_CONTRIBUTOR_POSITION);

        setId(id);
        setRaidContributorId(raidContributorId);
        setContributorPositionId(contributorPositionId);
        setStartDate(startDate);
        setEndDate(endDate);
    }
}
