/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.RaidDescription;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaidDescriptionRecord extends UpdatableRecordImpl<RaidDescriptionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.raid_description.id</code>.
     */
    public RaidDescriptionRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_description.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.raid_description.handle</code>.
     */
    public RaidDescriptionRecord setHandle(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_description.handle</code>.
     */
    public String getHandle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.raid_description.description_type_id</code>.
     */
    public RaidDescriptionRecord setDescriptionTypeId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_description.description_type_id</code>.
     */
    public Integer getDescriptionTypeId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>api_svc.raid_description.text</code>.
     */
    public RaidDescriptionRecord setText(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_description.text</code>.
     */
    public String getText() {
        return (String) get(3);
    }

    /**
     * Setter for <code>api_svc.raid_description.language_id</code>.
     */
    public RaidDescriptionRecord setLanguageId(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_description.language_id</code>.
     */
    public Integer getLanguageId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaidDescriptionRecord
     */
    public RaidDescriptionRecord() {
        super(RaidDescription.RAID_DESCRIPTION);
    }

    /**
     * Create a detached, initialised RaidDescriptionRecord
     */
    public RaidDescriptionRecord(Integer id, String handle, Integer descriptionTypeId, String text, Integer languageId) {
        super(RaidDescription.RAID_DESCRIPTION);

        setId(id);
        setHandle(handle);
        setDescriptionTypeId(descriptionTypeId);
        setText(text);
        setLanguageId(languageId);
    }
}
