/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.RaidSpatialCoverage;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaidSpatialCoverageRecord extends UpdatableRecordImpl<RaidSpatialCoverageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.raid_spatial_coverage.id</code>.
     */
    public RaidSpatialCoverageRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_spatial_coverage.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.raid_spatial_coverage.handle</code>.
     */
    public RaidSpatialCoverageRecord setHandle(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_spatial_coverage.handle</code>.
     */
    public String getHandle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.raid_spatial_coverage.uri</code>.
     */
    public RaidSpatialCoverageRecord setUri(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_spatial_coverage.uri</code>.
     */
    public String getUri() {
        return (String) get(2);
    }

    /**
     * Setter for <code>api_svc.raid_spatial_coverage.schema_id</code>.
     */
    public RaidSpatialCoverageRecord setSchemaId(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_spatial_coverage.schema_id</code>.
     */
    public Integer getSchemaId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaidSpatialCoverageRecord
     */
    public RaidSpatialCoverageRecord() {
        super(RaidSpatialCoverage.RAID_SPATIAL_COVERAGE);
    }

    /**
     * Create a detached, initialised RaidSpatialCoverageRecord
     */
    public RaidSpatialCoverageRecord(Integer id, String handle, String uri, Integer schemaId) {
        super(RaidSpatialCoverage.RAID_SPATIAL_COVERAGE);

        setId(id);
        setHandle(handle);
        setUri(uri);
        setSchemaId(schemaId);
    }
}
