/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.RaidSubjectKeyword;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaidSubjectKeywordRecord extends UpdatableRecordImpl<RaidSubjectKeywordRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.raid_subject_keyword.id</code>.
     */
    public RaidSubjectKeywordRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_subject_keyword.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.raid_subject_keyword.raid_subject_id</code>.
     */
    public RaidSubjectKeywordRecord setRaidSubjectId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_subject_keyword.raid_subject_id</code>.
     */
    public Integer getRaidSubjectId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>api_svc.raid_subject_keyword.keyword</code>.
     */
    public RaidSubjectKeywordRecord setKeyword(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_subject_keyword.keyword</code>.
     */
    public String getKeyword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>api_svc.raid_subject_keyword.language_id</code>.
     */
    public RaidSubjectKeywordRecord setLanguageId(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_subject_keyword.language_id</code>.
     */
    public Integer getLanguageId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaidSubjectKeywordRecord
     */
    public RaidSubjectKeywordRecord() {
        super(RaidSubjectKeyword.RAID_SUBJECT_KEYWORD);
    }

    /**
     * Create a detached, initialised RaidSubjectKeywordRecord
     */
    public RaidSubjectKeywordRecord(Integer id, Integer raidSubjectId, String keyword, Integer languageId) {
        super(RaidSubjectKeyword.RAID_SUBJECT_KEYWORD);

        setId(id);
        setRaidSubjectId(raidSubjectId);
        setKeyword(keyword);
        setLanguageId(languageId);
    }
}
