/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.RaidContributorRole;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaidContributorRoleRecord extends UpdatableRecordImpl<RaidContributorRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.raid_contributor_role.id</code>.
     */
    public RaidContributorRoleRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_contributor_role.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>api_svc.raid_contributor_role.raid_contributor_id</code>.
     */
    public RaidContributorRoleRecord setRaidContributorId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>api_svc.raid_contributor_role.raid_contributor_id</code>.
     */
    public Integer getRaidContributorId() {
        return (Integer) get(1);
    }

    /**
     * Setter for
     * <code>api_svc.raid_contributor_role.contributor_role_id</code>.
     */
    public RaidContributorRoleRecord setContributorRoleId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>api_svc.raid_contributor_role.contributor_role_id</code>.
     */
    public Integer getContributorRoleId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaidContributorRoleRecord
     */
    public RaidContributorRoleRecord() {
        super(RaidContributorRole.RAID_CONTRIBUTOR_ROLE);
    }

    /**
     * Create a detached, initialised RaidContributorRoleRecord
     */
    public RaidContributorRoleRecord(Integer id, Integer raidContributorId, Integer contributorRoleId) {
        super(RaidContributorRole.RAID_CONTRIBUTOR_ROLE);

        setId(id);
        setRaidContributorId(raidContributorId);
        setContributorRoleId(contributorRoleId);
    }
}
