/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.RaidTitle;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaidTitleRecord extends UpdatableRecordImpl<RaidTitleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.raid_title.id</code>.
     */
    public RaidTitleRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_title.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.raid_title.handle</code>.
     */
    public RaidTitleRecord setHandle(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_title.handle</code>.
     */
    public String getHandle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.raid_title.title_type_id</code>.
     */
    public RaidTitleRecord setTitleTypeId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_title.title_type_id</code>.
     */
    public Integer getTitleTypeId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>api_svc.raid_title.text</code>.
     */
    public RaidTitleRecord setText(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_title.text</code>.
     */
    public String getText() {
        return (String) get(3);
    }

    /**
     * Setter for <code>api_svc.raid_title.language_id</code>.
     */
    public RaidTitleRecord setLanguageId(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_title.language_id</code>.
     */
    public Integer getLanguageId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>api_svc.raid_title.start_date</code>.
     */
    public RaidTitleRecord setStartDate(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_title.start_date</code>.
     */
    public String getStartDate() {
        return (String) get(5);
    }

    /**
     * Setter for <code>api_svc.raid_title.end_date</code>.
     */
    public RaidTitleRecord setEndDate(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_title.end_date</code>.
     */
    public String getEndDate() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaidTitleRecord
     */
    public RaidTitleRecord() {
        super(RaidTitle.RAID_TITLE);
    }

    /**
     * Create a detached, initialised RaidTitleRecord
     */
    public RaidTitleRecord(Integer id, String handle, Integer titleTypeId, String text, Integer languageId, String startDate, String endDate) {
        super(RaidTitle.RAID_TITLE);

        setId(id);
        setHandle(handle);
        setTitleTypeId(titleTypeId);
        setText(text);
        setLanguageId(languageId);
        setStartDate(startDate);
        setEndDate(endDate);
    }
}
