/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.RaidSpatialCoveragePlace;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaidSpatialCoveragePlaceRecord extends TableRecordImpl<RaidSpatialCoveragePlaceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>api_svc.raid_spatial_coverage_place.raid_spatial_coverage_id</code>.
     */
    public RaidSpatialCoveragePlaceRecord setRaidSpatialCoverageId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for
     * <code>api_svc.raid_spatial_coverage_place.raid_spatial_coverage_id</code>.
     */
    public Integer getRaidSpatialCoverageId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.raid_spatial_coverage_place.place</code>.
     */
    public RaidSpatialCoveragePlaceRecord setPlace(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_spatial_coverage_place.place</code>.
     */
    public String getPlace() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.raid_spatial_coverage_place.language_id</code>.
     */
    public RaidSpatialCoveragePlaceRecord setLanguageId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.raid_spatial_coverage_place.language_id</code>.
     */
    public Integer getLanguageId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaidSpatialCoveragePlaceRecord
     */
    public RaidSpatialCoveragePlaceRecord() {
        super(RaidSpatialCoveragePlace.RAID_SPATIAL_COVERAGE_PLACE);
    }

    /**
     * Create a detached, initialised RaidSpatialCoveragePlaceRecord
     */
    public RaidSpatialCoveragePlaceRecord(Integer raidSpatialCoverageId, String place, Integer languageId) {
        super(RaidSpatialCoveragePlace.RAID_SPATIAL_COVERAGE_PLACE);

        setRaidSpatialCoverageId(raidSpatialCoverageId);
        setPlace(place);
        setLanguageId(languageId);
    }
}
