/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.RelatedRaid;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RelatedRaidRecord extends UpdatableRecordImpl<RelatedRaidRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.related_raid.handle</code>.
     */
    public RelatedRaidRecord setHandle(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.related_raid.handle</code>.
     */
    public String getHandle() {
        return (String) get(0);
    }

    /**
     * Setter for <code>api_svc.related_raid.related_raid_handle</code>.
     */
    public RelatedRaidRecord setRelatedRaidHandle(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.related_raid.related_raid_handle</code>.
     */
    public String getRelatedRaidHandle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.related_raid.related_raid_type_id</code>.
     */
    public RelatedRaidRecord setRelatedRaidTypeId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.related_raid.related_raid_type_id</code>.
     */
    public Integer getRelatedRaidTypeId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RelatedRaidRecord
     */
    public RelatedRaidRecord() {
        super(RelatedRaid.RELATED_RAID);
    }

    /**
     * Create a detached, initialised RelatedRaidRecord
     */
    public RelatedRaidRecord(String handle, String relatedRaidHandle, Integer relatedRaidTypeId) {
        super(RelatedRaid.RELATED_RAID);

        setHandle(handle);
        setRelatedRaidHandle(relatedRaidHandle);
        setRelatedRaidTypeId(relatedRaidTypeId);
    }
}
