/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.RelatedObject;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RelatedObjectRecord extends UpdatableRecordImpl<RelatedObjectRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.related_object.id</code>.
     */
    public RelatedObjectRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.related_object.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.related_object.pid</code>.
     */
    public RelatedObjectRecord setPid(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.related_object.pid</code>.
     */
    public String getPid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.related_object.schema_id</code>.
     */
    public RelatedObjectRecord setSchemaId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.related_object.schema_id</code>.
     */
    public Integer getSchemaId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RelatedObjectRecord
     */
    public RelatedObjectRecord() {
        super(RelatedObject.RELATED_OBJECT);
    }

    /**
     * Create a detached, initialised RelatedObjectRecord
     */
    public RelatedObjectRecord(Integer id, String pid, Integer schemaId) {
        super(RelatedObject.RELATED_OBJECT);

        setId(id);
        setPid(pid);
        setSchemaId(schemaId);
    }
}
