/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.enums.SchemaStatus;
import au.org.raid.db.jooq.tables.RelatedObjectSchema;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RelatedObjectSchemaRecord extends UpdatableRecordImpl<RelatedObjectSchemaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.related_object_schema.id</code>.
     */
    public RelatedObjectSchemaRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.related_object_schema.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.related_object_schema.uri</code>.
     */
    public RelatedObjectSchemaRecord setUri(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.related_object_schema.uri</code>.
     */
    public String getUri() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.related_object_schema.status</code>.
     */
    public RelatedObjectSchemaRecord setStatus(SchemaStatus value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.related_object_schema.status</code>.
     */
    public SchemaStatus getStatus() {
        return (SchemaStatus) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RelatedObjectSchemaRecord
     */
    public RelatedObjectSchemaRecord() {
        super(RelatedObjectSchema.RELATED_OBJECT_SCHEMA);
    }

    /**
     * Create a detached, initialised RelatedObjectSchemaRecord
     */
    public RelatedObjectSchemaRecord(Integer id, String uri, SchemaStatus status) {
        super(RelatedObjectSchema.RELATED_OBJECT_SCHEMA);

        setId(id);
        setUri(uri);
        setStatus(status);
    }
}
