/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.RelatedRaidType;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RelatedRaidTypeRecord extends UpdatableRecordImpl<RelatedRaidTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.related_raid_type.id</code>.
     */
    public RelatedRaidTypeRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.related_raid_type.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.related_raid_type.uri</code>.
     */
    public RelatedRaidTypeRecord setUri(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.related_raid_type.uri</code>.
     */
    public String getUri() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.related_raid_type.schema_id</code>.
     */
    public RelatedRaidTypeRecord setSchemaId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.related_raid_type.schema_id</code>.
     */
    public Integer getSchemaId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RelatedRaidTypeRecord
     */
    public RelatedRaidTypeRecord() {
        super(RelatedRaidType.RELATED_RAID_TYPE);
    }

    /**
     * Create a detached, initialised RelatedRaidTypeRecord
     */
    public RelatedRaidTypeRecord(Integer id, String uri, Integer schemaId) {
        super(RelatedRaidType.RELATED_RAID_TYPE);

        setId(id);
        setUri(uri);
        setSchemaId(schemaId);
    }
}
