/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.RelatedObjectCategory;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RelatedObjectCategoryRecord extends UpdatableRecordImpl<RelatedObjectCategoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.related_object_category.id</code>.
     */
    public RelatedObjectCategoryRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.related_object_category.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.related_object_category.uri</code>.
     */
    public RelatedObjectCategoryRecord setUri(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.related_object_category.uri</code>.
     */
    public String getUri() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.related_object_category.schema_id</code>.
     */
    public RelatedObjectCategoryRecord setSchemaId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.related_object_category.schema_id</code>.
     */
    public Integer getSchemaId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RelatedObjectCategoryRecord
     */
    public RelatedObjectCategoryRecord() {
        super(RelatedObjectCategory.RELATED_OBJECT_CATEGORY);
    }

    /**
     * Create a detached, initialised RelatedObjectCategoryRecord
     */
    public RelatedObjectCategoryRecord(Integer id, String uri, Integer schemaId) {
        super(RelatedObjectCategory.RELATED_OBJECT_CATEGORY);

        setId(id);
        setUri(uri);
        setSchemaId(schemaId);
    }
}
