/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.ServicePoint;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServicePointRecord extends UpdatableRecordImpl<ServicePointRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.service_point.id</code>.
     */
    public ServicePointRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.service_point.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>api_svc.service_point.name</code>.
     */
    public ServicePointRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.service_point.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.service_point.search_content</code>. Trimmed
     * lowercase only
     */
    public ServicePointRecord setSearchContent(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.service_point.search_content</code>. Trimmed
     * lowercase only
     */
    public String getSearchContent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>api_svc.service_point.admin_email</code>.
     */
    public ServicePointRecord setAdminEmail(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.service_point.admin_email</code>.
     */
    public String getAdminEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>api_svc.service_point.tech_email</code>.
     */
    public ServicePointRecord setTechEmail(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.service_point.tech_email</code>.
     */
    public String getTechEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>api_svc.service_point.enabled</code>.
     */
    public ServicePointRecord setEnabled(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.service_point.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>api_svc.service_point.lower_name</code>.
     */
    public ServicePointRecord setLowerName(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.service_point.lower_name</code>.
     */
    public String getLowerName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>api_svc.service_point.identifier_owner</code>.
     */
    public ServicePointRecord setIdentifierOwner(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.service_point.identifier_owner</code>.
     */
    public String getIdentifierOwner() {
        return (String) get(7);
    }

    /**
     * Setter for <code>api_svc.service_point.app_writes_enabled</code>.
     */
    public ServicePointRecord setAppWritesEnabled(Boolean value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.service_point.app_writes_enabled</code>.
     */
    public Boolean getAppWritesEnabled() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>api_svc.service_point.repository_id</code>.
     */
    public ServicePointRecord setRepositoryId(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.service_point.repository_id</code>.
     */
    public String getRepositoryId() {
        return (String) get(9);
    }

    /**
     * Setter for <code>api_svc.service_point.prefix</code>.
     */
    public ServicePointRecord setPrefix(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.service_point.prefix</code>.
     */
    public String getPrefix() {
        return (String) get(10);
    }

    /**
     * Setter for <code>api_svc.service_point.password</code>.
     */
    public ServicePointRecord setPassword(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.service_point.password</code>.
     */
    public String getPassword() {
        return (String) get(11);
    }

    /**
     * Setter for <code>api_svc.service_point.group_id</code>.
     */
    public ServicePointRecord setGroupId(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.service_point.group_id</code>.
     */
    public String getGroupId() {
        return (String) get(12);
    }

    /**
     * Setter for <code>api_svc.service_point.created</code>.
     */
    public ServicePointRecord setCreated(OffsetDateTime value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.service_point.created</code>.
     */
    public OffsetDateTime getCreated() {
        return (OffsetDateTime) get(13);
    }

    /**
     * Setter for <code>api_svc.service_point.updated</code>.
     */
    public ServicePointRecord setUpdated(OffsetDateTime value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.service_point.updated</code>.
     */
    public OffsetDateTime getUpdated() {
        return (OffsetDateTime) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ServicePointRecord
     */
    public ServicePointRecord() {
        super(ServicePoint.SERVICE_POINT);
    }

    /**
     * Create a detached, initialised ServicePointRecord
     */
    public ServicePointRecord(Long id, String name, String searchContent, String adminEmail, String techEmail, Boolean enabled, String lowerName, String identifierOwner, Boolean appWritesEnabled, String repositoryId, String prefix, String password, String groupId, OffsetDateTime created, OffsetDateTime updated) {
        super(ServicePoint.SERVICE_POINT);

        setId(id);
        setName(name);
        setSearchContent(searchContent);
        setAdminEmail(adminEmail);
        setTechEmail(techEmail);
        setEnabled(enabled);
        setLowerName(lowerName);
        setIdentifierOwner(identifierOwner);
        setAppWritesEnabled(appWritesEnabled);
        setRepositoryId(repositoryId);
        setPrefix(prefix);
        setPassword(password);
        setGroupId(groupId);
        setCreated(created);
        setUpdated(updated);
    }
}
