/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.enums.SchemaStatus;
import au.org.raid.db.jooq.tables.SpatialCoverageSchema;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpatialCoverageSchemaRecord extends UpdatableRecordImpl<SpatialCoverageSchemaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.spatial_coverage_schema.id</code>.
     */
    public SpatialCoverageSchemaRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.spatial_coverage_schema.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.spatial_coverage_schema.uri</code>.
     */
    public SpatialCoverageSchemaRecord setUri(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.spatial_coverage_schema.uri</code>.
     */
    public String getUri() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.spatial_coverage_schema.status</code>.
     */
    public SpatialCoverageSchemaRecord setStatus(SchemaStatus value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.spatial_coverage_schema.status</code>.
     */
    public SchemaStatus getStatus() {
        return (SchemaStatus) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpatialCoverageSchemaRecord
     */
    public SpatialCoverageSchemaRecord() {
        super(SpatialCoverageSchema.SPATIAL_COVERAGE_SCHEMA);
    }

    /**
     * Create a detached, initialised SpatialCoverageSchemaRecord
     */
    public SpatialCoverageSchemaRecord(Integer id, String uri, SchemaStatus status) {
        super(SpatialCoverageSchema.SPATIAL_COVERAGE_SCHEMA);

        setId(id);
        setUri(uri);
        setStatus(status);
    }
}
