/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.enums.SchemaStatus;
import au.org.raid.db.jooq.tables.SubjectTypeSchema;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubjectTypeSchemaRecord extends UpdatableRecordImpl<SubjectTypeSchemaRecord> implements Record4<Integer, String, SchemaStatus, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.subject_type_schema.id</code>.
     */
    public SubjectTypeSchemaRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.subject_type_schema.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.subject_type_schema.uri</code>.
     */
    public SubjectTypeSchemaRecord setUri(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.subject_type_schema.uri</code>.
     */
    public String getUri() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.subject_type_schema.status</code>.
     */
    public SubjectTypeSchemaRecord setStatus(SchemaStatus value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.subject_type_schema.status</code>.
     */
    public SchemaStatus getStatus() {
        return (SchemaStatus) get(2);
    }

    /**
     * Setter for <code>api_svc.subject_type_schema.id_starts_with</code>.
     */
    public SubjectTypeSchemaRecord setIdStartsWith(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.subject_type_schema.id_starts_with</code>.
     */
    public String getIdStartsWith() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, SchemaStatus, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, SchemaStatus, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return SubjectTypeSchema.SUBJECT_TYPE_SCHEMA.ID;
    }

    @Override
    public Field<String> field2() {
        return SubjectTypeSchema.SUBJECT_TYPE_SCHEMA.URI;
    }

    @Override
    public Field<SchemaStatus> field3() {
        return SubjectTypeSchema.SUBJECT_TYPE_SCHEMA.STATUS;
    }

    @Override
    public Field<String> field4() {
        return SubjectTypeSchema.SUBJECT_TYPE_SCHEMA.ID_STARTS_WITH;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUri();
    }

    @Override
    public SchemaStatus component3() {
        return getStatus();
    }

    @Override
    public String component4() {
        return getIdStartsWith();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUri();
    }

    @Override
    public SchemaStatus value3() {
        return getStatus();
    }

    @Override
    public String value4() {
        return getIdStartsWith();
    }

    @Override
    public SubjectTypeSchemaRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public SubjectTypeSchemaRecord value2(String value) {
        setUri(value);
        return this;
    }

    @Override
    public SubjectTypeSchemaRecord value3(SchemaStatus value) {
        setStatus(value);
        return this;
    }

    @Override
    public SubjectTypeSchemaRecord value4(String value) {
        setIdStartsWith(value);
        return this;
    }

    @Override
    public SubjectTypeSchemaRecord values(Integer value1, String value2, SchemaStatus value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SubjectTypeSchemaRecord
     */
    public SubjectTypeSchemaRecord() {
        super(SubjectTypeSchema.SUBJECT_TYPE_SCHEMA);
    }

    /**
     * Create a detached, initialised SubjectTypeSchemaRecord
     */
    public SubjectTypeSchemaRecord(Integer id, String uri, SchemaStatus status, String idStartsWith) {
        super(SubjectTypeSchema.SUBJECT_TYPE_SCHEMA);

        setId(id);
        setUri(uri);
        setStatus(status);
        setIdStartsWith(idStartsWith);
    }
}
