/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.enums.SchemaStatus;
import au.org.raid.db.jooq.tables.SubjectTypeSchema;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubjectTypeSchemaRecord extends UpdatableRecordImpl<SubjectTypeSchemaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.subject_type_schema.id</code>.
     */
    public SubjectTypeSchemaRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.subject_type_schema.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.subject_type_schema.uri</code>.
     */
    public SubjectTypeSchemaRecord setUri(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.subject_type_schema.uri</code>.
     */
    public String getUri() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.subject_type_schema.status</code>.
     */
    public SubjectTypeSchemaRecord setStatus(SchemaStatus value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.subject_type_schema.status</code>.
     */
    public SchemaStatus getStatus() {
        return (SchemaStatus) get(2);
    }

    /**
     * Setter for <code>api_svc.subject_type_schema.id_starts_with</code>.
     */
    public SubjectTypeSchemaRecord setIdStartsWith(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.subject_type_schema.id_starts_with</code>.
     */
    public String getIdStartsWith() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SubjectTypeSchemaRecord
     */
    public SubjectTypeSchemaRecord() {
        super(SubjectTypeSchema.SUBJECT_TYPE_SCHEMA);
    }

    /**
     * Create a detached, initialised SubjectTypeSchemaRecord
     */
    public SubjectTypeSchemaRecord(Integer id, String uri, SchemaStatus status, String idStartsWith) {
        super(SubjectTypeSchema.SUBJECT_TYPE_SCHEMA);

        setId(id);
        setUri(uri);
        setStatus(status);
        setIdStartsWith(idStartsWith);
    }
}
