/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.SubjectType;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubjectTypeRecord extends UpdatableRecordImpl<SubjectTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.subject_type.id</code>.
     */
    public SubjectTypeRecord setId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.subject_type.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>api_svc.subject_type.name</code>.
     */
    public SubjectTypeRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.subject_type.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.subject_type.description</code>.
     */
    public SubjectTypeRecord setDescription(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.subject_type.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>api_svc.subject_type.note</code>.
     */
    public SubjectTypeRecord setNote(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.subject_type.note</code>.
     */
    public String getNote() {
        return (String) get(3);
    }

    /**
     * Setter for <code>api_svc.subject_type.schema_id</code>.
     */
    public SubjectTypeRecord setSchemaId(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.subject_type.schema_id</code>.
     */
    public Integer getSchemaId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SubjectTypeRecord
     */
    public SubjectTypeRecord() {
        super(SubjectType.SUBJECT_TYPE);
    }

    /**
     * Create a detached, initialised SubjectTypeRecord
     */
    public SubjectTypeRecord(String id, String name, String description, String note, Integer schemaId) {
        super(SubjectType.SUBJECT_TYPE);

        setId(id);
        setName(name);
        setDescription(description);
        setNote(note);
        setSchemaId(schemaId);
    }
}
