/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.Token;

import java.time.LocalDateTime;

import org.jooq.JSONB;
import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * from
 * arn:aws:dynamodb:ap-southeast-2:005299621378:table/RAiD-TokenTable-1P6MFZ0WFEETH
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TokenRecord extends UpdatableRecordImpl<TokenRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.token.name</code>.
     */
    public TokenRecord setName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.token.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>api_svc.token.environment</code>.
     */
    public TokenRecord setEnvironment(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.token.environment</code>.
     */
    public String getEnvironment() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.token.date_created</code>.
     */
    public TokenRecord setDateCreated(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.token.date_created</code>.
     */
    public LocalDateTime getDateCreated() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>api_svc.token.token</code>.
     */
    public TokenRecord setToken(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.token.token</code>.
     */
    public String getToken() {
        return (String) get(3);
    }

    /**
     * Setter for <code>api_svc.token.s3_export</code>.
     */
    public TokenRecord setS3Export(JSONB value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.token.s3_export</code>.
     */
    public JSONB getS3Export() {
        return (JSONB) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<String, String, LocalDateTime> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TokenRecord
     */
    public TokenRecord() {
        super(Token.TOKEN);
    }

    /**
     * Create a detached, initialised TokenRecord
     */
    public TokenRecord(String name, String environment, LocalDateTime dateCreated, String token, JSONB s3Export) {
        super(Token.TOKEN);

        setName(name);
        setEnvironment(environment);
        setDateCreated(dateCreated);
        setToken(token);
        setS3Export(s3Export);
    }
}
