/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.TraditionalKnowledgeLabel;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TraditionalKnowledgeLabelRecord extends UpdatableRecordImpl<TraditionalKnowledgeLabelRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.traditional_knowledge_label.id</code>.
     */
    public TraditionalKnowledgeLabelRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.traditional_knowledge_label.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.traditional_knowledge_label.uri</code>.
     */
    public TraditionalKnowledgeLabelRecord setUri(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.traditional_knowledge_label.uri</code>.
     */
    public String getUri() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.traditional_knowledge_label.schema_id</code>.
     */
    public TraditionalKnowledgeLabelRecord setSchemaId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.traditional_knowledge_label.schema_id</code>.
     */
    public Integer getSchemaId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TraditionalKnowledgeLabelRecord
     */
    public TraditionalKnowledgeLabelRecord() {
        super(TraditionalKnowledgeLabel.TRADITIONAL_KNOWLEDGE_LABEL);
    }

    /**
     * Create a detached, initialised TraditionalKnowledgeLabelRecord
     */
    public TraditionalKnowledgeLabelRecord(Integer id, String uri, Integer schemaId) {
        super(TraditionalKnowledgeLabel.TRADITIONAL_KNOWLEDGE_LABEL);

        setId(id);
        setUri(uri);
        setSchemaId(schemaId);
    }
}
