/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.enums.SchemaStatus;
import au.org.raid.db.jooq.tables.TraditionalKnowledgeNoticeSchema;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TraditionalKnowledgeNoticeSchemaRecord extends UpdatableRecordImpl<TraditionalKnowledgeNoticeSchemaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.traditional_knowledge_notice_schema.id</code>.
     */
    public TraditionalKnowledgeNoticeSchemaRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.traditional_knowledge_notice_schema.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.traditional_knowledge_notice_schema.uri</code>.
     */
    public TraditionalKnowledgeNoticeSchemaRecord setUri(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.traditional_knowledge_notice_schema.uri</code>.
     */
    public String getUri() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>api_svc.traditional_knowledge_notice_schema.status</code>.
     */
    public TraditionalKnowledgeNoticeSchemaRecord setStatus(SchemaStatus value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>api_svc.traditional_knowledge_notice_schema.status</code>.
     */
    public SchemaStatus getStatus() {
        return (SchemaStatus) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TraditionalKnowledgeNoticeSchemaRecord
     */
    public TraditionalKnowledgeNoticeSchemaRecord() {
        super(TraditionalKnowledgeNoticeSchema.TRADITIONAL_KNOWLEDGE_NOTICE_SCHEMA);
    }

    /**
     * Create a detached, initialised TraditionalKnowledgeNoticeSchemaRecord
     */
    public TraditionalKnowledgeNoticeSchemaRecord(Integer id, String uri, SchemaStatus status) {
        super(TraditionalKnowledgeNoticeSchema.TRADITIONAL_KNOWLEDGE_NOTICE_SCHEMA);

        setId(id);
        setUri(uri);
        setStatus(status);
    }
}
