/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.tables.TraditionalKnowledgeNotice;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TraditionalKnowledgeNoticeRecord extends UpdatableRecordImpl<TraditionalKnowledgeNoticeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.traditional_knowledge_notice.id</code>.
     */
    public TraditionalKnowledgeNoticeRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.traditional_knowledge_notice.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>api_svc.traditional_knowledge_notice.uri</code>.
     */
    public TraditionalKnowledgeNoticeRecord setUri(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.traditional_knowledge_notice.uri</code>.
     */
    public String getUri() {
        return (String) get(1);
    }

    /**
     * Setter for <code>api_svc.traditional_knowledge_notice.schema_id</code>.
     */
    public TraditionalKnowledgeNoticeRecord setSchemaId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.traditional_knowledge_notice.schema_id</code>.
     */
    public Integer getSchemaId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TraditionalKnowledgeNoticeRecord
     */
    public TraditionalKnowledgeNoticeRecord() {
        super(TraditionalKnowledgeNotice.TRADITIONAL_KNOWLEDGE_NOTICE);
    }

    /**
     * Create a detached, initialised TraditionalKnowledgeNoticeRecord
     */
    public TraditionalKnowledgeNoticeRecord(Integer id, String uri, Integer schemaId) {
        super(TraditionalKnowledgeNotice.TRADITIONAL_KNOWLEDGE_NOTICE);

        setId(id);
        setUri(uri);
        setSchemaId(schemaId);
    }
}
