/*
 * This file is generated by jOOQ.
 */
package au.org.raid.db.jooq.tables.records;


import au.org.raid.db.jooq.enums.AuthRequestStatus;
import au.org.raid.db.jooq.enums.IdProvider;
import au.org.raid.db.jooq.tables.UserAuthzRequest;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAuthzRequestRecord extends UpdatableRecordImpl<UserAuthzRequestRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>api_svc.user_authz_request.id</code>.
     */
    public UserAuthzRequestRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.user_authz_request.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>api_svc.user_authz_request.status</code>.
     */
    public UserAuthzRequestRecord setStatus(AuthRequestStatus value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.user_authz_request.status</code>.
     */
    public AuthRequestStatus getStatus() {
        return (AuthRequestStatus) get(1);
    }

    /**
     * Setter for <code>api_svc.user_authz_request.service_point_id</code>.
     */
    public UserAuthzRequestRecord setServicePointId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.user_authz_request.service_point_id</code>.
     */
    public Long getServicePointId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>api_svc.user_authz_request.email</code>. Lowercase chars
     * only - db enforced
     */
    public UserAuthzRequestRecord setEmail(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.user_authz_request.email</code>. Lowercase chars
     * only - db enforced
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>api_svc.user_authz_request.client_id</code>.
     */
    public UserAuthzRequestRecord setClientId(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.user_authz_request.client_id</code>.
     */
    public String getClientId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>api_svc.user_authz_request.id_provider</code>.
     */
    public UserAuthzRequestRecord setIdProvider(IdProvider value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.user_authz_request.id_provider</code>.
     */
    public IdProvider getIdProvider() {
        return (IdProvider) get(5);
    }

    /**
     * Setter for <code>api_svc.user_authz_request.subject</code>.
     */
    public UserAuthzRequestRecord setSubject(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.user_authz_request.subject</code>.
     */
    public String getSubject() {
        return (String) get(6);
    }

    /**
     * Setter for <code>api_svc.user_authz_request.responding_user</code>. user
     * that approved or rejected, not set until that happens
     */
    public UserAuthzRequestRecord setRespondingUser(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.user_authz_request.responding_user</code>. user
     * that approved or rejected, not set until that happens
     */
    public Long getRespondingUser() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>api_svc.user_authz_request.approved_user</code>. the
     * user that was approved, set when request is approved and the
     *   user is created or updated
     */
    public UserAuthzRequestRecord setApprovedUser(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.user_authz_request.approved_user</code>. the
     * user that was approved, set when request is approved and the
     *   user is created or updated
     */
    public Long getApprovedUser() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>api_svc.user_authz_request.description</code>.
     */
    public UserAuthzRequestRecord setDescription(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.user_authz_request.description</code>.
     */
    public String getDescription() {
        return (String) get(9);
    }

    /**
     * Setter for <code>api_svc.user_authz_request.date_requested</code>.
     */
    public UserAuthzRequestRecord setDateRequested(LocalDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.user_authz_request.date_requested</code>.
     */
    public LocalDateTime getDateRequested() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>api_svc.user_authz_request.date_responded</code>. not
     * set until approved or rejected
     */
    public UserAuthzRequestRecord setDateResponded(LocalDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>api_svc.user_authz_request.date_responded</code>. not
     * set until approved or rejected
     */
    public LocalDateTime getDateResponded() {
        return (LocalDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserAuthzRequestRecord
     */
    public UserAuthzRequestRecord() {
        super(UserAuthzRequest.USER_AUTHZ_REQUEST);
    }

    /**
     * Create a detached, initialised UserAuthzRequestRecord
     */
    public UserAuthzRequestRecord(Long id, AuthRequestStatus status, Long servicePointId, String email, String clientId, IdProvider idProvider, String subject, Long respondingUser, Long approvedUser, String description, LocalDateTime dateRequested, LocalDateTime dateResponded) {
        super(UserAuthzRequest.USER_AUTHZ_REQUEST);

        setId(id);
        setStatus(status);
        setServicePointId(servicePointId);
        setEmail(email);
        setClientId(clientId);
        setIdProvider(idProvider);
        setSubject(subject);
        setRespondingUser(respondingUser);
        setApprovedUser(approvedUser);
        setDescription(description);
        setDateRequested(dateRequested);
        setDateResponded(dateResponded);
    }
}
