https://marineregions.org/gazetteer.php|Marine gazeteer URI
https://nominatim.openstreetmap.org/|Openstreetmap link
https://vocabulary.raid.org/spatialCoverage.schemaUri/1|Openstreetmap URL
https://vocabulary.raid.org/spatialCoverage.schemaUri/2|Geonames concept URI
https://www.geonames.org/|Geonames document URI
https://www.openstreetmap.org/|Openstreetmap link